export const TASK_REQUEST = "GET_USER_TASKS_REQUEST";
export const TASK_FAILED = "GET_USER_TASKS_FAILED";

export const GET_USER_TASKS_SUCCESS = "GET_USER_TASKS_SUCCESS";

export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";

export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";

export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const SHARE_TASK_SUCCESS = "SHARE_TASK_SUCCESS";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const SHARE_TASK_REQUEST = "SHARE_TASK_REQUEST";
export const RESET_TASK = "RESET_TASK";
export const RESET_ERROR = "RESET_ERROR";

export const CLEAR_TASKS = "CLEAR_TASKS";
